services:
  frontend:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
